### PR TITLE
Add vote

### PR DESCRIPTION
**Pull request by adetoye-dev**

### CODE REVIEW

**Comment by adetoye-dev** [comment]
I would have said thanks for accepting my PR, but yunno who cares? 😂

**Comment by adetoye-dev** [comment]
Anyways, love the idea 🙂👏

**Comment by GrahamTheDevRel** [comment]
I haven't seen you host for ages and didn't see you in the convo sooooo...my bad?

Also although I like to troll, I would say that comments on GitHub are the wrong place for us to take the micky, so lets do that on Twitter and keep these semi-professional bud! 🙏💗

**Comment by adetoye-dev** [comment]
Yeah, I've been off twitter for a while 🙂

Sure, thanks for the merge. See you around on Twitter  😊👍

**Pull request merged**
